networks:
  micromind-network:
    driver: bridge

services:
  micromind:
    build: .
    ports:
      - 8080:8080
    environment:
      MONGO_USERNAME: ricky
      MONGO_PASSWORD: first
      MONGO_ENDPOINT: mongodb:27017
    networks:
      micromind-network:
        aliases:
          - micromind

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ricky
      MONGO_INITDB_ROOT_PASSWORD: first
      MONGO_INITDB_DATABASE: micromind
    ports:
      - "27017:27017"
    networks:
      micromind-network:
        aliases:
          - mongodb
    volumes:
      - ./init-mongodb:/docker-entrypoint-initdb.d/
      - ./init-mongodb/data:/tmp/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - micromind-network
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana/grafana-dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      micromind-network:
        aliases:
          - prometheus

  influxdb:
    image: influxdb:1.8
    networks:
      - micromind-network
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  k6:
    image: loadimpact/k6:latest
    networks:
      - micromind-network
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./performance_scripts:/scripts

